### ISSUE TITLE
Add Styling to Buttons in Footer

### ISSUE THREAD

**Issue by Pat-Brennan** [Pat-Brennan/Self-Checkout-UI#25]
- They're identical to the Envisionware buttons, but I think we can do better 😎

**Comment by keyniev** [comment]
Do you have any ideas? I was going to keep them as is so I'm kinda stuck on this! Maybe a minimal change? I think there's a fine line for the footer of there looking like there's a lot going on at once because of the purple footer being a bit difficult to match other colors with.

**Comment by Pat-Brennan** [comment]
No worries! I was considering more subtle stylistic stuff I think! Changing the font to match the rest of the UI, Maybe changing the color to a similar off-white like the cards instead of the default light grey, made adding a bit of border-radius to make them less edgy and pointy.

Just some ideas!
